name: recursive_regex
description: >-
  An implementation of RegExp that isolates delimited blocks of
  text and applies the pattern to each block separately.
version: 0.1.0
author: James Alexander <j.alex@email.com>
homepage: https://github.com/james-alex/recursive_regex

environment:
  sdk: ">=2.1.0 <3.0.0"

dev_dependencies:
  test: ^1.6.5
