name: recursive_regex
description: >-
  An implementation of RegExp that isolates delimited blocks of
  text and applies the pattern to each block separately.
version: 0.2.0
homepage: https://github.com/james-alex/recursive_regex

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.3.0

dev_dependencies:
  test: ^1.16.8
  pedantic: ^1.11.0
